### ISSUE TITLE
Windows build error

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#1]
Msys2
I need find and add some jsonrpc-glib-1.0 VAPI right?
```shell
$ meson build --buildtype=release && ninja -C build
The Meson build system
Version: 0.52.0
Source dir: C:/msys64/home/gavr/vala-language-server-alpha-master
Build dir: C:/msys64/home/gavr/vala-language-server-alpha-master/build
Build type: native build
Project name: vala-language-server
Project version: undefined
C compiler for the host machine: cc (gcc 9.2.0 "cc (Rev2, Built by MSYS2 project) 9.2.0")
C linker for the host machine: GNU ld.bfd 2.32
Vala compiler for the host machine: valac (valac 0.46.2)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: C:\msys64\mingw64\bin/pkg-config.EXE (0.29.2)
WARNING: No include directory found parsing "cc -xc -E -v -" output
Run-time dependency glib-2.0 found: YES 2.62.1
Run-time dependency gobject-2.0 found: YES 2.62.1
Run-time dependency gee-0.8 found: YES 0.20.2
Run-time dependency gio-2.0 found: YES 2.62.1
Run-time dependency jsonrpc-glib-1.0 found: YES 3.33.3
Run-time dependency libvala-0.46 found: YES 0.46.2-dirty
Run-time dependency gio-windows-2.0 found: YES 2.62.1
Message: vala_version: Vala 0.46.2
Build targets in project: 1
Found ninja.EXE-1.9.0 at C:\msys64\mingw64\bin/ninja.EXE
ninja: Entering directory `build'
[1/17] Compiling Vala source ../JsonSerializable.vapi ../windows.vapi ../Main.vala ../Server.vala ../Protocol.vala ../Reporter.vala ../Context.vala ../FindNode.vala ../FindNodeInFile.vala ../FindNodeByPosition.vala ../FindSymbolByPosition.vala ../FindSymbolByName.vala ../FindSymbolReferences.vala ../FindSymbolsInFile.vala ../CodeHelpers.vala ../JsonHelpers.vala ../MiscHelpers.vala.
FAILED: vala-language-server@exe/Main.c vala-language-server@exe/Server.c vala-language-server@exe/Protocol.c vala-language-server@exe/Reporter.c vala-language-server@exe/Context.c vala-language-server@exe/FindNode.c vala-language-server@exe/FindNodeInFile.c vala-language-server@exe/FindNodeByPosition.c vala-language-server@exe/FindSymbolByPosition.c vala-language-server@exe/FindSymbolByName.c vala-language-server@exe/FindSymbolReferences.c vala-language-server@exe/FindSymbolsInFile.c vala-language-server@exe/CodeHelpers.c vala-language-server@exe/JsonHelpers.c vala-language-server@exe/MiscHelpers.c
valac "-C" "--define=WINDOWS" "--enable-gobject-tracing" "--disable-warnings" "--define" "NDEBUG" "--pkg=posix" "--pkg" "gio-windows-2.0" "--pkg" "libvala-0.46" "--pkg" "jsonrpc-glib-1.0" "--pkg" "gio-2.0" "--pkg" "gee-0.8" "--pkg" "gobject-2.0" "--target-glib" "2.54" "--pkg" "glib-2.0" "--color=always" "--directory" "vala-language-server@exe" "--basedir" "../" ../JsonSerializable.vapi ../windows.vapi ../Main.vala ../Server.vala ../Protocol.vala ../Reporter.vala ../Context.vala ../FindNode.vala ../FindNodeInFile.vala ../FindNodeByPosition.vala ../FindSymbolByPosition.vala ../FindSymbolByName.vala ../FindSymbolReferences.vala ../FindSymbolsInFile.vala ../CodeHelpers.vala ../JsonHelpers.vala ../MiscHelpers.vala
Compilation failed: 1 error(s), 0 warning(s)
error: Package `jsonrpc-glib-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
ninja: build stopped: subcommand failed.
```
PS Dude, thank you so much for tackling the tooling problem for Vala. Let me ask you a question - why? I dont see Vala repositories among your projects, and you said that the main development environment is Windows, what do you use Vala for?

**Comment by gavr123456789** [comment]
I compiled with VAPI from the ArchLinux [package](https://www.archlinux.org/packages/extra/x86_64/jsonrpc-glib/). But now I have an error when starting Language Server:  
```
[Info  - 19:59:02] Connection to server got closed. Server will restart.
[Info  - 19:59:02] Connection to server got closed. Server will restart.
[Info  - 19:59:02] Connection to server got closed. Server will restart.
[Info  - 19:59:02] Connection to server got closed. Server will restart.
[Error - 19:59:02] Connection to server got closed. Server will not be restarted.
```

**Comment by gavr123456789** [comment]
there with Trace:Server parameter = messages
```
[Info  - 20:03:30] Connection to server got closed. Server will restart.
[Trace - 20:03:30] Sending request 'initialize - (0)'.
[Error - 20:03:30] Connection to server got closed. Server will not be restarted.
```

```
[Trace - 20:39:42] Sending request 'initialize - (0)'.
Running in Windows (debug build)...
** INFO: 20:39:42.365: Server.vala:171: root_uri (file:///c%3A/Users/gavr/Documents/Vala/languageServerTest), root_path (c:\Users\gavr\Documents\Vala\languageServerTest)

** (process:5604): CRITICAL **: 20:39:42.365: file vala-language-server@exe/Server.c: line 2081: uncaught error: Cannot find 'meson.build' (error-quark, 0)
```

**Comment by philippejer** [comment]
Sorry about the late answer, totally missed it...

Yes absolutely, the VAPI is missing from the package for some reason, I've actually just created an issue about it: https://github.com/msys2/MINGW-packages/issues/5860

I've taken the VAPI from archlinux just as you did...

**Comment by philippejer** [comment]
About your error, I think this is because one of the pre-requisites is to use Meson to build the project (it is mentioned in the README but it might not be very clear that you actually need to have a `meson.build` file in your project)...

For a basic test you should be able to use a minimal build file (see: https://mesonbuild.com/Vala.html)

As an alternative, it would be very easy to let the user have some kind of `vala-language-server.json` file at the root of his project with a simple list of the source files, the packages and the compiler switches.

Note that I'm currently cleaning up and commenting the code a bit (should be finished soon hopefully).

**Comment by philippejer** [comment]
About my use of Vala, I was looking for a better C (or a native C# depending on how you see it) and was disappointed by the (many) alternatives I tried (C++ obviously, Go, Rust, Nim, D, Haxe, probably others that I've forgotten).

I'd like to use Vala for (toy) game engine development under Windows but not sure if I'll ever publish some source code as it is a sandbox and it currently depends on proprietary assets (!).

**Comment by philippejer** [comment]
I've added some MinGW-64 installation steps in the [README](https://github.com/philippejer/vala-language-server-alpha/blob/master/README.md)

Just tested it recently on a new machine and had no issues, hopefully I did not forget anything...

**Comment by gavr123456789** [comment]
@philippejer  Nice, thank you very much. I'm kind of a fan of this language(translated the main guide and some materials into my language), and I'm very curious why you chose it, why not "C++ obviously, Go, Rust, Nim, D, Haxe," 
Okay, C++ is not safe, Go and D have Stop The World GC. What about the others?

**Comment by philippejer** [comment]
Hi,

Just saw your answer from 21 days ago (!)...

I guess the reason I like Vala is mostly because it's kind of a native equivalent of C# and I like C# for its "straightforwardness"...

There are many interesting things in these other languages (Rust is especially impressive, I'd love to use it for a professional project) but I guess in the end I just want a simple object-oriented C with no gimmicks and no hand-holding ;)

- Rust is not object-oriented (apart for some very limited simili-inheritance).

- Go is not object-oriented and has a huge native call overhead (I think x10 or x20 compared to even C# or Java) due to its concurrency model, which can be problematic in an OpenGL application which makes lots of native calls per frame. Also, it is very opinionated and does not allow shared memory (uses channels), just like Nim.

- C++ is the obvious answer but it has way too much legacy for me, for example I just don't have the patience for the header/implementation prototype duplication (for a "fun" project, anyway)... Also, using smart pointers does not feel part of the language like in Vala even though they are part of the standard.

- D is a great language but I think it has become way too complex and does not seem to know where it wants to be (it seems to be trying to copy Rust these days)...
