### ISSUE TITLE
New option for Windows

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#10]
What about the new Windows option "path to msys or something" (to parse all Vapi from there)  to get rid of the need to use both Meson and vala-language-server-test.json (If only meson needed)

**Comment by philippejer** [comment]
Hi @gavr123456789 

I'm not sure I understand completely...

If you are referring to the binary package, the problem is that the VAPIs are located by the Vala compiler using [this GLib function](https://developer.gnome.org/glib/stable/glib-Miscellaneous-Utility-Functions.html#g-get-system-data-dirs), which looks for the `share` folder in the parent directory of where `libvala.dll` is located...

So if you have `/mingw64/bin` in your path and the Vala compiler is installed, you actually only need `vala-language-server.exe`, but I wanted to have a self-contained binary package to troubleshoot issues (some sort of reference point which is known to work).

**Comment by gavr123456789** [comment]
Now it is possible to create vala-language-server-test.json to as far as I understand provide the ability to use VSL without adding Vala to the PATH. How about creating a "Path to MSYS2/bin" parameter. 
 
To end up with 2 path parameters, one to the VSL itself.exe and second to MSYS2 for parsing libraries and APIs. Then vala-language-server-test.json will not be needed.

**Comment by gavr123456789** [comment]
I think it will just be assumed that the mingw/bin folder is added to the PATH.
