### ISSUE TITLE
add json-rpc.vapi to README

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#13]
Add instructions on how to add json-rpc.vapi instructions for compiling for Windows.

**Comment by gavr123456789** [comment]
I'm talking about where to download and [where](https://www.archlinux.org/packages/extra/x86_64/jsonrpc-glib/) to put(mingw64\share\vala\vapi) jsonrpc-glib-1.0.api  
May be even put that file to repo.

**Comment by philippejer** [comment]
Hi sorry about the long delay, have been swamped again lately...

Good point, I have added a note in the README (https://github.com/philippejer/vala-language-server-alpha/commit/3e6797c653d46b349cebedd6066c616fdd3b6ecf).

Note: I have checked and actually the bug has been fixed in MSYS2 (https://github.com/msys2/MINGW-packages/issues/5860), the latest package has the VAPI.
