### ISSUE TITLE
Works in tests

### ISSUE THREAD

**Issue by gavr123456789** [philippejer/vala-language-server-alpha#18]
I just noticed that autocomplete only works in the first of the tests because:  
```shell
WARNING **: 07:47:39.899: Server.vala:676: Multiple executable targets found in Meson build file, additional executable target will be ignored: 'html5-test' (executable) ignored
```
Project to test https://github.com/arteymix/compose  
VLS works fo compose-test.vala, but not for htm5.

**Comment by philippejer** [comment]
Hi @gavr123456789,

Thanks for the feedback and sorry for the delay, I will (normally) have more time during the holidays.

This is very useful, I tend to work with a single project and a single executable so I did not have the opportunity to test this kind of more sophisticated build with multiple executables...

At first I wanted to add an option to explicitly select the list of targets to load into the compiler context (the problem is that you can only load one executable target at any one point, otherwise you'll have duplicate symbols, like `main()`).

But I think it is not difficult to do better and select the targets dynamically based on the list of opened file(s):

- When a source file is opened, find the corresponding build target(s) and mark it as "enabled" if necessary.
- If the target is executable and another executable is already enabled, disable that other target.
- Rebuild the compiler context with the enabled targets, if a target has been enabled or disabled.

Seems fairly simple, I'll try to do it later today and update :)

**Comment by gavr123456789** [comment]
Also recently wrote this a small [article-guide](https://vala.gitbook.io/vala/techniques/unit-tests) about unit tests in Meson and Vala. It's in Russian, but you can turn on auto-translation.  
  
double Also: Just [created](https://github.com/kostya/benchmarks/pull/217) a popular benchmark test on the brainfuck compiler for Vala. And in my tests C++ 2.01 sec, C# 4 sec, Vala 1.81 sec!
I love this language.

**Comment by philippejer** [comment]
Hi @gavr123456789,

Thanks for the link, very useful info, it might be a good idea to feed it back to the GNOME Wiki (and GitBook is also much more pleasant to read than the old-school Wiki!).

I have had the time to implement the approach above (https://github.com/philippejer/vala-language-server-alpha/commit/0bd3b705e25d2ddf0947d57eaedb64303d09edbd), it was a bit more complex to implement than expected, but a good opportunity to clean up a few things.

It seems to work fine on your project, please tell me if you still have issues,
Jeremy

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/71078057-b34b7080-2199-11ea-8f5e-e7ab508d1105.png)
Thank you, Yes I'm in a group of trusted editors, and for a while I was finishing the guide on Vala on their wiki, but there is so inconvenient markup (it's not MD, its something more ancient) that I decided to make a guide on GitBook and put a link to it in the documentation list. https://wiki.gnome.org/Projects/Vala/Documentation  
So I just keep adding links to interesting projects down there. Think can transfer documentation on other languages to GitBook.  
  
Nice, will test it  evening.

**Comment by gavr123456789** [comment]
Works great now!
