### ISSUE TITLE
Interested in merging efforts

### ISSUE THREAD

**Issue by Prince781** [philippejer/vala-language-server-alpha#35]
This project started off as a fork of https://github.com/benwaffle/vala-language-server, which I believe was partly motivated by the inadequate pace of development on VLS at the time. Since then, we've improved things massively, with support for various project backends, improved completion support, and performance improvements. 
I am thankful for the work you've done here and I hope that if you're still interested in this sort of thing you'd consider joining the VLS project as a contributor.

**Comment by philippejer** [comment]
Hi @Prince781

Sorry for the lack of answer, I could not work on Vala these past months for personal reasons...

But I'm slowly getting back into it (mostly playing with some hacks in the compiler :-) )

I definitely want to put this project in maintenance mode to avoid confusion (I still want to push an update for Vala 0.48 and a few bugfixes here and there).

I think I could make useful contributions to your project (maybe more on the VSCode specific stuff since I think you're using vim primarily).

I'm currently on vacation but I'll have some time to look at it more closely next week.

Thanks for reaching out :-)

**Comment by Prince781** [comment]
Thanks for the reply. There's just one thing I need to correct you on:

> (maybe more on the VSCode specific stuff since I think you're using vim primarily

Actually we've primarily been working on VSCode with vim taking second place on our priority (but it's a close second). However, our goals are to support every editor out there, and to that end we also have been working on GNOME Builder support and there is discussion of how to bring support to Elementary's Code editor.

**Comment by Prince781** [comment]
Also, if/when you do decide to check out the VLS codebase, I'd be more than happy to help you out with any questions you have about it.
